version: "3.4"

services:
  server:
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app/

  client:
    network_mode: host
    build:
      context: .
      dockerfile: ./examples/client/Dockerfile
    command:
      - /client --list && /client --add  && /client --list
    volumes:
      - .:/app/